### ISSUE TITLE
Data files not included when TopoNetX package is built

### ISSUE THREAD

**Issue by Hellsegga** [pyt-team/TopoNetX#195] opened 2023-07-12 10:57 UTC
If I run `pip install '.[all]'` i.e. not in editable mode with the `-e` option (or if I get TopoNetX as dependency from TopoModelX), then data files (such as bunny.obj and coauthorship.npy in https://github.com/pyt-team/TopoNetX/tree/main/toponetx/datasets) are excluded.

I believe something has to be changed in the setuptools/.toml file config for the right files to be included (https://setuptools.pypa.io/en/latest/userguide/datafiles.html).

**Comment by devendragovil** [comment] 2023-09-12 10:26
After a lot of attempts, I think that the issue is with all builds. For me the -e option doesn't impact the build, datasets are included in both builds if I git clone the repo toponetx. I am attempting to solve via the draft PR #239

**Comment by ffl096** [comment] 2024-08-01 12:24
Fixed in #381.

**Closed by ffl096** 2024-08-01 12:24 UTC
