### ISSUE TITLE
Error when computing the incidence matrix of rank 2 on SHREC dataset

### ISSUE THREAD

**Issue by abdelwahed** [pyt-team/TopoNetX#167] opened 2023-06-15 06:59 UTC
I tried to call the `SimplicialComplex.incidence_matrix` (rank 2) on the shrec dataset  using the code below 

``` python
import toponetx.datasets as datasets

shrec, _ = datasets.mesh.shrec_16(size="small")
simplexes = shrec["complexes"]
print(simplexes[0].incidence_matrix(rank=2))
```

I get the following error (KeyError) 

``` bash
 File "/snap/pycharm-professional/336/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/kha053/PycharmProjects/TopoNetX/tutorials/test.py", line 19, in <module>
    print(simplexes[0].incidence_matrix(rank=2))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kha053/PycharmProjects/TopoNetX/toponetx/classes/simplicial_complex.py", line 783, in incidence_matrix
    idx_faces.append(simplex_dict_d_minus_1[tuple(face)])
                     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: (89, 81)
```

Similar errors are shown for `SimplicialComplex.up_laplacian_matrix` and `SimplicialComplex.down_laplacian_matrix`.

**Comment by ffl096** [comment] 2023-06-15 07:17
I think this is a duplicate of #154 and should be fixed with #155 is merged.

**Comment by mhajij** [comment] 2023-06-17 01:52
@abdelwahed this has been addressed now. Please pull the new version.

**Comment by abdelwahed** [comment] 2023-06-21 01:00
Thanks @mhajij

**Closed** 2023-06-21 06:54 UTC
Labels: bug
